---
title: "Analisi_chanceDistribution"
author: "Elena"
date: '2023-04-13'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
knitr::opts_chunk$set( warning=FALSE, message=FALSE,                   # default code chunk options
                      fig.width=15, fig.height=8, fig.align="center", comment=NA, # default figure dimensions
                      fig.path="./figures_Final/",                                      # save images to ./figures/
                      dpi=300)
```

```{r , include=F, message=F, warning=FALSE}

library(knitr) # for opts_knitr and having captions to figures
library(data.table) # read some dataframe
library(tidyr) # for data processing
library(dplyr) # for data processing
library(ggplot2) # for plotting
library(rstatix) # for basic statistical test
library(stringr) #string operation
library(gridExtra) # a few others functions for plotting
library(heatmaply) # for correlation matric
library(caret) # for confusion matrix
library(nnet) # multinomial regression
library(lme4) # for glmer function
library(Hmisc) # for function cut2
library(tibble) # for data processing
library(car) # for vif function
library(FactoMineR) # for PCA
library(factoextra) # also for PCA
library(MASS)
library(readr)
library(fitdistrplus)
library(tidyverse)
library(magrittr)
library(reshape2)
library(ggpubr)
library(readxl)
library(emmeans)
library(gghalves)
library(gapminder)
library(ggside)
library(RcmdrMisc)
library(wesanderson)
library(lemon)
library(gtable)
library(ggh4x)

library(R.matlab)
library(combinat)
library(pracma)

se <- function(x) sd(x, na.rm = TRUE)/sqrt(length(x))

knitr::opts_chunk$set(warning=FALSE, message=FALSE,                   # default code chunk options
                      fig.width=11, fig.height=6, fig.align="center", comment=NA, # default figure dimensions
                      fig.path="./figures_Analysis_Chance_Distr/",  dev=c("png", "svg"),                                  # save images to ./figures/
                      dpi=300)
```


```{r}
#  arr <- array(1:10, dim = c(1,10))
# #
# # # Transpose the array
# # new_arr <- t(arr)
# #
#  null_x = perms(new_arr)
# # #
# # # # Initialize vectors
#  r <- numeric(nrow(null_x))
#  pr <- numeric(nrow(null_x))
# # #
# # 
# # # Loop through rows of null_x
#  for (n in 1:nrow(null_x)) {
#    # Calculate correlation using Kendall's method
#    cor_res <- cor.test(null_x[n,], new_arr, method = "kendall")
# 
#    # Store correlation coefficient and p-value
#    r[n] <- cor_res$estimate
#    pr[n] <- cor_res$p.value
#  }

#save(r,null_x,cor_res, file = "C:/Users/elena.eccher-1/Desktop/Spanumbra_All/Spanumbra/Results/Permutation_Distr.Rdata")

```


```{r warning=FALSE, include=FALSE}


Tau_Dots =  read_csv("C:/Users/elena.eccher-1/Desktop/Spanumbra_All/Spanumbra/Results/ALL_tau_coef_Dots.csv")
Tau_Dots= Tau_Dots[Tau_Dots$Task == "Free",]
Tau_Dots = Tau_Dots %>%
  mutate(exp = case_when(exp == "Adults" ~ "Italian Adults",
                         exp == "Preschooler" ~ "Italian Preschooler",
                         exp == "Himba 2021" ~ "Himba Adults 2021",
                         exp == "Himba 2022" ~ "Himba Adults 2022",
                         T ~ exp))

load("C:/Users/elena.eccher-1/Desktop/Spanumbra_All/Spanumbra/Results/Permutation_Distr.Rdata")


```

```{r message=FALSE, warning=FALSE}
#::kable(table(r))

dr <- diff(unique(r))

# Define edges for histogram bins
edges_r <- seq(-1 - dr[1]/2, 1 + dr[1]/2, dr[1])

# Compute histogram counts and probabilities
nr <- hist(r, breaks = edges_r, plot = FALSE)$counts
pr <- nr / sum(nr)

# Create a data frame for plotting
df <- data.frame(rho = edges_r[-1], prob = pr, Distribution = "Chance")

# Plot the distribution
ggplot(df, aes(x = rho, y = prob)) + 
  geom_bar(stat = "identity") + 
  labs(x = "Kendall's tau", y = "Probability") + 
  theme_classic()



nr_adults <- hist(Tau_Dots[Tau_Dots$exp == "Italian Adults",]$cor, breaks = edges_r, plot = FALSE)$counts
pr_adults <- nr_adults / sum(nr_adults)

nr_Himba2021 <- hist(Tau_Dots[Tau_Dots$exp == "Himba Adults 2021",]$cor, breaks = edges_r, plot = FALSE)$counts
pr_Himba2021 <- nr_Himba2021 / sum(nr_Himba2021)

nr_Himba2022 <- hist(Tau_Dots[Tau_Dots$exp == "Himba Adults 2022",]$cor, breaks = edges_r, plot = FALSE)$counts
pr_Himba2022 <- nr_Himba2022 / sum(nr_Himba2022)

nr_pres <- hist(Tau_Dots[Tau_Dots$exp == "Italian Preschooler",]$cor, breaks = edges_r, plot = FALSE)$counts
pr_pres <- nr_pres / sum(nr_pres)

# Create a data frame for plotting
df_adults <- data.frame(rho = edges_r[-1], prob = pr_adults, exp = "Italian Adults",  Distribution = "Real")
df_Himba2021 <- data.frame(rho = edges_r[-1], prob = pr_Himba2021, exp = "Himba Adults 2021",  Distribution = "Real")
df_Himba2022 <- data.frame(rho = edges_r[-1], prob = pr_Himba2022, exp = "Himba Adults 2022", Distribution = "Real")
df_pres <- data.frame(rho = edges_r[-1], prob = pr_pres, exp = "Italian Preschooler", Distribution = "Real")

df_all = rbind(df_adults, df_Himba2021, df_Himba2022, df_pres) 

max_values = df_all%>%
  group_by(exp) %>%
  mutate(max_value= max(prob)) %>%
group_by(exp) %>%
  slice(1)



tab_distr = Tau_Dots %>%
  group_by(exp, Task) %>%
  summarise(mean_cor= mean(cor),
            se_cor = se(cor), 
            count = n())

stat.test <- Tau_Dots %>% 
  group_by(exp,  Task, Stimuli) %>%
  wilcox_test(cor ~ 1, mu = 0) %>%
  add_significance()  %>%
  add_xy_position(fun = "mean_se", x = 1)



effect_size <- Tau_Dots %>% 
  group_by(exp,  Task, Stimuli) %>%
  rstatix::wilcox_effsize(cor ~ 1, mu = 0)
effect_size




stat.test$p = round(stat.test$p, 3)

df_all$exp =factor(df_all$exp, levels = c("Italian Adults", "Himba Adults 2021", "Himba Adults 2022", "Italian Preschooler"))
tab_distr$exp =factor(tab_distr$exp, levels = c("Italian Adults", "Himba Adults 2021", "Himba Adults 2022", "Italian Preschooler"))
stat.test$exp =factor(stat.test$exp, levels = c("Italian Adults", "Himba Adults 2021", "Himba Adults 2022", "Italian Preschooler"))
```


```{r message=FALSE, warning=FALSE}
# Plot the distribution
plot = ggplot() + 
  geom_bar(data = df, aes(x = rho, y = prob, fill= Distribution),alpha = .5,stat = "identity") + 
  geom_bar(data = df_all, aes(x = rho, y = prob,  fill= Distribution),stat = "identity", alpha=.5) + 
  scale_fill_manual(values = c("gray", "red"))+
  facet_grid(. ~ exp )+
  geom_point(data = tab_distr, aes(x = mean_cor, y = 1.1), size = 3, show.legend = F)+
 geom_errorbarh(data = tab_distr, aes(xmin = mean_cor-se_cor, xmax =mean_cor+se_cor, y =1.1, height = .05),linewidth =  1, )+
 geom_text(data = tab_distr[tab_distr$Task == "Free" ,], aes( x = tab_distr[tab_distr$Task == "Free" ,]$mean_cor-.08, y= 1.25,label = paste0("n = ",count)))+
geom_text(data = stat.test[stat.test$Stimuli == "Dots" & stat.test$Task == "Free",], aes(x = tab_distr[tab_distr$Task == "Free" ,]$mean_cor-.08, y = 1.2,label = paste0("p_value = ",p)))+
  theme_bw(base_size = 15)+
   labs(x = "Right to Left <--- Correlation Coefficients ---> Left-to-Right", title = "R Distributions for Dots Task", subtitle = "p_value for Wilcoxon test against chance levele (mu = 0) are reported", y = "Probability")


plot
```


```{r message=FALSE, warning=FALSE}
p_adults <- ggplot() + 
    geom_vline(xintercept = 0, color = "grey", linetype ="dashed", alpha = .7, size = 1)+
  geom_bar(data = df, aes(x = rho, y = prob, fill = Distribution), alpha = .5, stat = "identity", show.legend = F) + 
  geom_bar(data = df_all[df_all$exp == "Italian Adults",], aes(x = rho, y = prob,  fill = Distribution), stat = "identity", show.legend = F) + 
  geom_point(data = tab_distr[tab_distr$exp == "Italian Adults",], aes(x = mean_cor, y =max_values[max_values$exp == "Italian Adults",]$max_value + 0.1 * max_values[max_values$exp == "Italian Adults",]$max_value), size = 1.5, show.legend = F) +
  geom_errorbarh(data = tab_distr[tab_distr$exp == "Italian Adults",], aes(xmin = mean_cor - se_cor, xmax = mean_cor + se_cor, y  =max_values[max_values$exp == "Italian Adults",]$max_value + 0.1 * max_values[max_values$exp == "Italian Adults",]$max_value, height = 0.1 * max_values[max_values$exp == "Italian Adults",]$max_value), height = .03) +
  #geom_text(data = tab_distr[tab_distr$Task == "Free", ], aes(x = tab_distr[tab_distr$Task == "Free" ,]$mean_cor-.08, y =max_values$max_value + 0.25 * max_values$max_value, label = paste0("n = ", count)))+
  #geom_text(data = stat.test[stat.test$Stimuli == "Dots" & stat.test$Task == "Free" & stat.test$exp == "Italian Adults",], aes(x = tab_distr[tab_distr$Task == "Free" & tab_distr$exp == "Italian Adults",]$mean_cor, y =max_values[max_values$exp == "Italian Adults",]$max_value + 0.2 * max_values[max_values$exp == "Italian Adults",]$max_value,label = p.signif))+
  coord_cartesian(xlim=c(-1.05,1.05))+
  theme_classic()+
   theme(panel.grid.major.y = element_blank(), 
        panel.grid.major.x = element_line(), 
         strip.background = element_blank(), 
         strip.text = element_text(size = rel(1.2)),
         aspect.ratio = 1 , 
         axis.title.y = element_text(size = 10),
         axis.text.y = element_text(size = 10),
         legend.position = "bottom",
         plot.title = element_text(size = 14, face = "bold"))+ 
        #plot.margin = margin(0.1,0.1,2,0.1, "cm"))+
  scale_fill_manual(values = c("gray", "red"))+
scale_y_continuous( breaks = seq(0, 1, by = 0.2))+
  labs(y = "Probability", x ="   Rightward                    Leftward")


p_adults
```


```{r message=FALSE, warning=FALSE}
p_himba_2021 <- ggplot() +
  geom_vline(xintercept = 0, color = "grey", linetype ="dashed", alpha = .7, size = 1)+
  geom_bar(data = df, aes(x = rho, y = prob, fill = Distribution), alpha = .5, stat = "identity") + 
  geom_bar(data = df_all[df_all$exp == "Himba Adults 2021",], aes(x = rho, y = prob,  fill = Distribution), stat = "identity") + 
  geom_point(data = tab_distr[tab_distr$exp== "Himba Adults 2021",], aes(x = mean_cor, y =.395), size = 1.5, show.legend = F) +
  geom_errorbarh(data = tab_distr[tab_distr$exp == "Himba Adults 2021",], aes(xmin = mean_cor - se_cor, xmax = mean_cor + se_cor, y  = .395), height = .015) +
  #geom_text(data = stat.test[stat.test$Stimuli == "Dots" & stat.test$Task == "Free" & stat.test$exp == "Himba 2021",], aes(x = tab_distr[tab_distr$Task == "Free" & tab_distr$exp == "Himba 2021",]$mean_cor, y =max_values[max_values$exp == "Himba 2021",]$max_value + 0.2 * max_values[max_values$exp == "Himba 2021",]$max_value,label = p.signif))+
  coord_cartesian(xlim=c(-1.05,1.05), ylim=c(0,.4))+
  theme_classic()+
   theme(panel.grid.major.y = element_blank(), 
        panel.grid.major.x = element_line(), 
         strip.background = element_blank(), 
         strip.text = element_text(size = rel(1.2)),
         aspect.ratio = 1 , 
         axis.title.y = element_text(size = 10),
         axis.text.y = element_text(size = 10),
         legend.position = "none",
         plot.title = element_text(size = 14, face = "bold"))+ 
        #plot.margin = margin(0.1,0.1,2,0.1, "cm"))+
  scale_fill_manual(values = c("gray", "red"))+
  labs(y = "Probability", x ="   Rightward                    Leftward")


p_himba_2021
```


```{r message=FALSE, warning=FALSE}
p_himba22 <- ggplot() + 
    geom_vline(xintercept = 0, color = "grey", linetype ="dashed", alpha = .7, size = 1)+
  geom_bar(data = df, aes(x = rho, y = prob, fill = Distribution), alpha = .5, stat = "identity") + 
  geom_bar(data = df_all[df_all$exp == "Himba Adults 2022",], aes(x = rho, y = prob,  fill = Distribution), stat = "identity") + 
  geom_point(data = tab_distr[tab_distr$exp  == "Himba Adults 2022",], aes(x = mean_cor, y =.395), size = 1.5, show.legend = F) +
  geom_errorbarh(data = tab_distr[tab_distr$exp  == "Himba Adults 2022",], aes(xmin = mean_cor - se_cor, xmax = mean_cor + se_cor, y  = .395), height = .015) +
  #geom_text(data = stat.test[stat.test$Stimuli == "Dots" & stat.test$Task == "Free" & stat.test$exp  == "Himba 2022",], aes(x = tab_distr[tab_distr$Task == "Free" & tab_distr$exp  == "Himba 2022",]$mean_cor, y =max_values[max_values$exp  == "Himba 2022",]$max_value + 0.2 * max_values[max_values$exp  == "Himba 2022",]$max_value,label = p.signif))+
  coord_cartesian(xlim=c(-1.05,1.05), ylim=c(0,.4))+
  theme_classic()+
   theme(panel.grid.major.y = element_blank(), 
        panel.grid.major.x = element_line(), 
         strip.background = element_blank(), 
         strip.text = element_text(size = rel(1.2)),
         aspect.ratio = 1 , 
         axis.title.y = element_text(size = 10),
         axis.text.y = element_text(size = 10),
         legend.position = "none",
         plot.title = element_text(size = 14, face = "bold"))+
        #plot.margin = margin(0.1,0.1,2,0.1, "cm"))+
  scale_fill_manual(values = c("gray", "red"))+
  labs(y = "Probability", x ="   Rightward                    Leftward")


p_himba22
```


```{r message=FALSE, warning=FALSE}
p_pres <- ggplot() + 
  geom_vline(xintercept = 0, color = "grey", linetype ="dashed", alpha = .7, size = 1)+
  geom_bar(data = df, aes(x = rho, y = prob, fill = Distribution), alpha = .5, stat = "identity") + 
  geom_bar(data = df_all[df_all$exp  == "Italian Preschooler",], aes(x = rho, y = prob,  fill = Distribution), stat = "identity") + 
  geom_point(data = tab_distr[tab_distr$exp == "Italian Preschooler",], aes(x = mean_cor, y =.395), size = 1.5, show.legend = F) +
  geom_errorbarh(data = tab_distr[tab_distr$exp == "Italian Preschooler",], aes(xmin = mean_cor - se_cor, xmax = mean_cor + se_cor, y  = .395), height = .015) +
  #geom_text(data = stat.test[stat.test$Stimuli == "Dots" & stat.test$Task == "Free" & stat.test$exp == "Italian Preschooler",], aes(x = tab_distr[tab_distr$Task == "Free" & tab_distr$exp == "Italian Preschooler",]$mean_cor, y =max_values[max_values$exp !== "Italian Preschooler",]$max_value + 0.2 * max_values[max_values$exp == "Italian Preschooler",]$max_value,label = p.signif))+
  coord_cartesian(xlim=c(-1.05,1.05), ylim=c(0,.4))+
  theme_classic()+
   theme(panel.grid.major.y = element_blank(), 
        panel.grid.major.x = element_line(), 
         strip.background = element_blank(), 
         strip.text = element_text(size = rel(1.2)),
         aspect.ratio = 1 , 
         axis.title.y = element_text(size = 10),
         axis.text.y = element_text(size = 10),
         legend.position = "none",
         plot.title = element_text(size = 14, face = "bold"))+
        #plot.margin = margin(0.1,0.1,2,0.1, "cm"))+
  scale_fill_manual(values = c("gray", "red"))+
  labs(y = "Probability", x ="   Rightward                    Leftward")


p_pres
```


```{r message=FALSE, warning=FALSE}

plot_all = ggarrange(p_adults, p_himba_2021, p_himba22,p_pres, ncol = 4)
plot_all
```







